apiVersion: v1
kind: Service
metadata:
  name: rag-retriever
  namespace: llm-app
  labels:
    app: rag-retriever
spec:
  type: NodePort
  selector:
    app: rag-retriever
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    nodePort: 31001
